server:
  proxy:
    - target: "http://localhost:5000/" # Base URL <string> of your backend
      prefix: "/users/" # Path <string>
    - target: "http://localhost:3000/"
      prefix: "/data/"
      replace: "/report/" # Replacement <string> of path in redirected URL (optional)
    - target: "http://localhost:4000/"
      prefix: "/products/"
      replace: ""
      web:
        renderer: html
        auto_detect: true

      web_development:
        host: 192.168.88.77
        port: 3020
        https:
          # This tells the server to generate a self-signed certificate for local development
          self_signed: true
